# Generated by Django 4.2.7 on 2023-11-24 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=225)),
                ('last_name', models.CharField(default='', max_length=225)),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=225)),
                ('userType', models.CharField(default='', max_length=50)),
                ('language', models.CharField(default='', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
